app/user/forms.py
from flask_wtf import FlaskForm
from wtforms import (StringField, PasswordField, BooleanField, SubmitField)
from wtforms.validators import InputRequired, ValidationError, Email, EqualTo
from app.models import User


class AddUserForm(FlaskForm):
    first_name = StringField('First Name', validators=[InputRequired()])
    last_name = StringField('Last Name', validators=[InputRequired()])
    email = StringField('Email', validators=[InputRequired(), Email()])
    phone = StringField('Phone', validators=[InputRequired()])
    username = StringField('Username', validators=[InputRequired()])
    password = PasswordField('Password', validators=[InputRequired()])
    password_2 = PasswordField('Repeat Password', validators=[InputRequired(), EqualTo('password')])
    submit = SubmitField('Register')

    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user is not None:
            raise ValidationError('Please use a different username')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user is not None:
            raise ValidationError('Please use a different email')


class EditUserForm(FlaskForm):
    first_name = StringField('First Name', validators=[InputRequired()])
    last_name = StringField('Last Name', validators=[InputRequired()])
    email = StringField('Email', validators=[InputRequired(), Email()])
    phone = StringField('Phone', validators=[InputRequired()])
    submit = SubmitField('Save')


class ChangePasswordForm(FlaskForm):
    old_password = PasswordField('Old Password', validators=[InputRequired()])
    password = PasswordField('Password', validators=[InputRequired()])
    password_2 = PasswordField('Repeat Password', validators=[InputRequired(), EqualTo('password')])
    submit = SubmitField('Change Password')


class DeleteUserForm(FlaskForm):
    confirm = BooleanField('Confirm')
    submit = SubmitField('Submit')

app/user/__init__.py
from flask import Blueprint

bp = Blueprint('user', __name__, template_folder='templates')

from app.user import routes

app/user/routes.py
from flask import render_template, flash, redirect, url_for
from flask_login import current_user, logout_user, login_required
from app import db
from app.models import User
from app.user.forms import (AddUserForm, EditUserForm, ChangePasswordForm, DeleteUserForm)
from app.user import bp


@bp.route('/view_users')
@login_required
def view_users():
    users = User.query.all()
    return render_template('view_users.html', title='Users', users=users)


@bp.route('/view_user/<user_id>')
@login_required
def view_user(user_id):
    user = User.query.get(int(user_id))
    return render_template('view_user.html', title='User Dashboard', user=user)


@bp.route('/add_user', methods=['GET', 'POST'])
@login_required
def add_user():
    form = AddUserForm()
    if form.validate_on_submit():
        user = User(first_name=form.first_name.data, last_name=form.last_name.data,
                    username=form.username.data, email=form.email.data, phone=form.phone.data)
        user.set_password(form.password.data)
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('user.view_user', user_id=user.id))
    return render_template('add_user.html', title='Add User', form=form)


@bp.route('/edit_user/<user_id>', methods=['GET', 'POST'])
@login_required
def edit_user(user_id):
    user = User.query.get(int(user_id))
    form = EditUserForm()
    if form.validate_on_submit():
        user.first_name = form.first_name.data
        user.last_name = form.last_name.data
        user.email = form.email.data
        user.phone = form.phone.data
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('user.view_user', user_id=user.id))
    form.first_name.data = user.first_name
    form.last_name.data = user.last_name
    form.email.data = user.email
    form.phone.data = user.phone
    return render_template('edit_user.html', title='Edit User', form=form)


@bp.route('/change_password/<user_id>', methods=['GET', 'POST'])
@login_required
def change_password(user_id):
    user = User.query.get(int(user_id))
    form = ChangePasswordForm()
    if form.validate_on_submit():
        if user.check_password(form.old_password.data):
            user.set_password(form.password.data)
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('user.view_user', user_id=user.id))
        else:
            flash('The password provided was not correct')
            return redirect(url_for('main.change_password', user_id=user.id))
    return render_template('change_password.html', title='Change Password', form=form)


@bp.route('/delete_user/<user_id>', methods=['GET', 'POST'])
@login_required
def delete_user(user_id):
    user = User.query.get(int(user_id))
    form = DeleteUserForm()
    if form.validate_on_submit():
        if form.confirm.data:
            if current_user.id == user.id:
                logout_user()
            db.session.delete(user)
            db.session.commit()
            return redirect(url_for('main.index'))
        else:
            return redirect(url_for('main.index'))
    return render_template('delete_user.html', title='Delete User', form=form, user=user)

app/user/templates/add_user.html
{% extends "base.html" %}
{% from 'bootstrap/form.html' import render_form %}

{% block app_content %}
    <h1>Add User</h1>
    <div class="row">
        <div class="col-md-4">
            {{ render_form(form) }}
        </div>
    </div>
{% endblock %}

app/user/templates/change_password.html
{% extends "base.html" %}
{% from 'bootstrap/form.html' import render_form %}

{% block app_content %}
    <h1>Change Password</h1>
    <p><b>Instruction: </b>Provide the old password followed by the new password and confirm.</p>
    <div class="row">
        <div class="col-md-4">
            {{ render_form(form) }}
        </div>
    </div>
{% endblock %}

app/user/templates/delete_user.html
{% extends "base.html" %}
{% from 'bootstrap/form.html' import render_form %}

{% block app_content %}
    <h1>Delete User</h1>
    <p><b>Instructions: </b>If you're sure you want to delete <b>{{ user.username }}</b>, check the confirmation box.</p>
    <p>Else, navigate to another page or submit without checking the confirmation box.</p>
    <div class="row">
        <div class="col-md-4">
            {{ render_form(form) }}
        </div>
    </div>
{% endblock %}

app/user/templates/edit_user.html
{% extends "base.html" %}
{% from 'bootstrap/form.html' import render_form %}

{% block app_content %}
    <h1>Edit User</h1>
    <div class="row">
        <div class="col-md-4">
            {{ render_form(form) }}
        </div>
    </div>
{% endblock %}

app/user/templates/view_user.html
{% extends "base.html" %}

{% block app_content %}
    <h1>User: {{ user.username }}</h1>
    <div class="row">
        <div class="col-md-4">
            <a href="{{ url_for('user.edit_user', user_id=user.id) }}" class="btn btn-primary" role="button">Edit Profile</a>
            {% if current_user.id == user.id %}
            <a href="{{ url_for('user.change_password', user_id=user.id) }}" class="btn btn-primary" role="button">Change Password</a>
            {% endif %}
            <a href="{{ url_for('user.delete_user', user_id=user.id) }}" class="btn btn-danger" role="button">Delete User</a>
        </div>
    </div>
    <div>
        <h2>User Information</h2>
        <table class="table">
            <tr>
                <td><b>Name: </b>{{ user.get_name() }}</td>
            </tr>
            <tr>
                <td><b>Email Address: </b>{{ user.email }}</td>
            </tr>
            <tr>
                <td><b>Phone: </b>{{ user.phone }}</td>
            </tr>
        </table>
    </div>
{% endblock %}

app/user/templates/view_users.html
{% extends "base.html" %}

{% block app_content %}
    <h1>Users</h1>
    <div class="table-responsive">
        <table class="table">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Username</th>
                    <th>Email</th>
                    <th>Phone</th>
                    <th>Delete User</th>
                </tr>
            </thead>
            <tbody>
            {% for user in users %}
                <tr>
                    <td><a href="{{ url_for('user.view_user', user_id=user.id) }}">{{ user.get_name() }}</a></td>
                    <td>{{ user.username }}</td>
                    <td>{{ user.email }}</td>
                    <td>{{ user.phone }}</td>
                    <td><a href="{{ url_for('user.delete_user', user_id=user.id) }}" class="btn btn-danger" role="button">Delete</a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}