app/account/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileRequired, FileAllowed
from wtforms import (StringField, BooleanField, SubmitField, SelectField, FloatField)
from wtforms.validators import InputRequired


class AccountForm(FlaskForm):
    custodian = SelectField('Custodian')
    account_number = StringField('Account Number')
    description = StringField('Description', validators=[InputRequired()])
    billable = BooleanField('Billable')
    discretionary = BooleanField('Discretionary')
    fee_schedule = SelectField('Fee Schedule')
    submit = SubmitField('Save')


class CustodianForm(FlaskForm):
    name = StringField('Name', validators=[InputRequired()])
    description = StringField('Description')
    submit = SubmitField('Save')


class UploadFileForm(FlaskForm):
    upload_file = FileField('File', validators=[FileRequired(), FileAllowed(['csv'], '.csv only')])
    submit = SubmitField('Upload')


class ExportToFileForm(FlaskForm):
    filename = StringField('Filename', validators=[InputRequired()])
    submit = SubmitField('Export')

app/account/__init__.py
from flask import Blueprint

bp = Blueprint('account', __name__, template_folder='templates')

from app.account import routes

app/account/routes.py
from flask import render_template, redirect, url_for
from flask_login import login_required
from app import db
from app.models import (Client, Account, Custodian, Quarter)
from app.account.forms import (AccountForm, CustodianForm, UploadFileForm,
                               ExportToFileForm)
from app.account import bp
from app.route_helpers import (get_custodian_choices, get_fee_schedule_choices, upload_file,
                               process_account_csv_file)
from werkzeug.utils import secure_filename
import os


@bp.route('/view_accounts')
@login_required
def view_accounts():
    accounts = Account.query.all()
    return render_template('view_accounts.html', title='Accounts', accounts=accounts)


@bp.route('/view_account/<account_id>')
@login_required
def view_account(account_id):
    account = Account.query.get(int(account_id))
    positions = account.positions
    transactions = account.transactions
    snapshots = account.snapshots
    return render_template('view_account.html', title='Account Dashboard', account=account,
                           positions=positions, transactions=transactions, snapshots=snapshots)


@bp.route('/add_account/<client_id>', methods=['GET', 'POST'])
@login_required
def add_account(client_id):
    client = Client.query.get(int(client_id))
    form = AccountForm()
    custodian_choices = get_custodian_choices()
    fee_schedule_choices = get_fee_schedule_choices()
    form.custodian.choices = custodian_choices
    form.fee_schedule.choices = fee_schedule_choices
    if form.validate_on_submit():
        if form.fee_schedule.data == 'None':
            schedule_id = None
        else:
            schedule_id = form.fee_schedule.data
        account = Account(account_number=form.account_number.data, description=form.description.data,
                          discretionary=form.discretionary.data, billable=form.billable.data,
                          client_id=client.id, group_id=client.group_id, custodian_id=form.custodian.data,
                          schedule_id=schedule_id)
        db.session.add(account)
        db.session.commit()
        return redirect(url_for('account.view_account', account_id=account.id))
    return render_template('add_account.html', title='Add Account', form=form, client=client)


@bp.route('/upload_accounts', methods=['GET', 'POST'])
@login_required
def upload_accounts():
    form = UploadFileForm()
    if form.validate_on_submit():
        f = form.upload_file.data
        process_account_csv_file(file_object=f)
        return redirect(url_for('account.view_accounts'))
    return render_template('upload_account_file.html', title='Upload Accounts', form=form)


@bp.route('/export_accounts', methods=['GET', 'POST'])
@login_required
def export_accounts():
    form = ExportToFileForm()
    if form.validate_on_submit():
        filename = os.path.join('exports/' + secure_filename(form.filename.data))
        with open(filename, 'w') as export_file:
            export_file.write('Account Number,Description,Client First Name,Client Last Name,' +
                              'Custodian,Billable,Discretionary\n')
            accounts = Account.query.all()
            for account in accounts:
                export_file.write(account.export_account_csv() + '\n')
        return redirect(url_for('main.index'))
    return render_template('export_accounts.html', title='Export Accounts', form=form)


@bp.route('/edit_account/<account_id>', methods=['GET', 'POST'])
@login_required
def edit_account(account_id):
    account = Account.query.get(int(account_id))
    form = AccountForm()
    custodian_choices = get_custodian_choices()
    fee_schedule_choices = get_fee_schedule_choices()
    form.custodian.choices = custodian_choices
    form.fee_schedule.choices = fee_schedule_choices
    if form.validate_on_submit():
        account.account_number = form.account_number.data
        account.description = form.description.data
        account.billable = form.billable.data
        account.discretionary = form.discretionary.data
        if form.fee_schedule.data == 'None':
            schedule_id = None
        else:
            schedule_id = form.fee_schedule.data
        account.schedule_id = schedule_id
        db.session.add(account)
        db.session.commit()
        return redirect(url_for('account.view_account', account_id=account.id))
    form.account_number.data = account.account_number
    form.description.data = account.description
    form.billable.data = account.billable
    form.discretionary.data = account.discretionary
    return render_template('edit_account.html', title='Edit Account', form=form)


@bp.route('/delete_account/<account_id>')
@login_required
def delete_account(account_id):
    account = Account.query.get(int(account_id))
    for snapshot in account.snapshots:
        quarter = Quarter.query.get(snapshot.quarter_id)
        quarter.aum -= snapshot.market_value
        quarter.fee -= snapshot.fee
        db.session.delete(snapshot)
        db.session.add(quarter)
    db.session.delete(account)
    db.session.commit()
    return redirect(url_for('account.view_accounts'))


@bp.route('/delete_all_accounts')
@login_required
def delete_all_accounts():
    accounts = Account.query.all()
    for account in accounts:
        db.session.delete(account)
    db.session.commit()
    return redirect(url_for('main.index'))


@bp.route('/view_custodians')
@login_required
def view_custodians():
    custodians = Custodian.query.all()
    return render_template('view_custodians.html', title='Custodians', custodians=custodians)


@bp.route('/view_custodian/<custodian_id>')
@login_required
def view_custodian(custodian_id):
    custodian = Custodian.query.get(int(custodian_id))
    return render_template('view_custodian.html', title='Custodian Dashboard', custodian=custodian)


@bp.route('/add_custodian', methods=['GET', 'POST'])
@login_required
def add_custodian():
    form = CustodianForm()
    if form.validate_on_submit():
        custodian = Custodian(name=form.name.data, description=form.description.data)
        db.session.add(custodian)
        db.session.commit()
        return redirect(url_for('account.view_custodian', custodian_id=custodian.id))
    return render_template('add_custodian.html', title='Add Custodian', form=form)


@bp.route('/edit_custodian/<custodian_id>', methods=['GET', 'POST'])
@login_required
def edit_custodian(custodian_id):
    custodian = Custodian.query.get(int(custodian_id))
    form = CustodianForm()
    if form.validate_on_submit():
        custodian.name = form.name.data
        custodian.description = form.description.data
        db.session.add(custodian)
        db.session.commit()
        return redirect(url_for('account.view_custodian', custodian_id=custodian.id))
    form.name.data = custodian.name
    form.description.data = custodian.description
    return render_template('edit_custodian.html', title='Edit Custodian', form=form)

app/account/templates/add_account.html
{% extends "base.html" %}
{% from 'bootstrap/form.html' import render_form %}

{% block app_content %}
    <h1>Add Account</h1>
    <p><b>Instructions: </b>Fill out the form below to create an account for {{ client.get_name()}}</p>
    <div class="row">
        <div class="col-md-4">
            {{ render_form(form) }}
        </div>
    </div>
{% endblock %}

app/account/templates/add_custodian.html
{% extends "base.html" %}
{% from 'bootstrap/form.html' import render_form %}

{% block app_content %}
    <h1>Add Custodian</h1>
    <p><b>Instructions: </b>Fill out the form below to create a new custodian.</p>
    <div class="row">
        <div class="col-md-4">
            {{ render_form(form) }}
        </div>
    </div>
{% endblock %}

app/account/templates/edit_account.html
{% extends "base.html" %}
{% from 'bootstrap/form.html' import render_form %}

{% block app_content %}
    <h1>Edit Account</h1>
    <p><b>Instructions: </b>Make changes to the form below to edit the account.</p>
    <div class="row">
        <div class="col-md-4">
            {{ render_form(form) }}
        </div>
    </div>
{% endblock %}

app/account/templates/edit_custodian.html
{% extends "base.html" %}
{% from 'bootstrap/form.html' import render_form %}

{% block app_content %}
    <h1>Edit Custodian</h1>
    <p><b>Instructions: </b>Fill out the form below to edit the custodian.</p>
    <div class="row">
        <div class="col-md-4">
            {{ render_form(form) }}
        </div>
    </div>
{% endblock %}

app/account/templates/export_accounts.html
{% extends "base.html" %}
{% from 'bootstrap/form.html' import render_form %}

{% block app_content %}
    <h1>Export Accounts to CSV</h1>
    <div class="row">
        <div class="col-md-4">
            {{ render_form(form) }}
        </div>
    </div>
{% endblock %}

app/account/templates/upload_account_file.html
{% extends "base.html" %}
{% from 'bootstrap/form.html' import render_form %}

{% block app_content %}
    <h1>Upload Account File</h1>
    <p><b>Instructions: </b>Use the form to upload a .csv file.</p>
    <p>Account Number | Description | First Name | Last Name | Custodian | Billable | Discretionary</p>
    <div class="row">
        <div class="col-md-4">
            {{ render_form(form) }}
        </div>
    </div>
{% endblock %}

app/account/templates/view_account.html
{% extends "base.html" %}

{% block app_content %}
    <h1>Account Dashboard</h1>
    <div class="row">
        <div class="col-md-12">
            <a href="{{ url_for('transaction.add_transaction', account_id=account.id) }}" class="btn btn-primary" role="button">Add Transaction</a>
            <a href="{{ url_for('account.edit_account', account_id=account.id) }}" class="btn btn-primary" role="button">Edit Account</a>
            <a href="{{ url_for('billing.add_account_snapshot', account_id=account.id) }}" class="btn btn-primary" role="button">Add Account Snapshot</a>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <h2>Account Information</h2>
            <p><b>Account Number: </b>{{ account.account_number }}</p>
            <p><b>Client: </b><a href="{{ url_for('client.view_client', client_id=account.client_id) }}">{{ account.get_client_name() }}</a></p>
            <p><b>Custodian: </b><a href="{{ url_for('account.view_custodian', custodian_id=account.custodian_id) }}">{{ account.get_custodian_name() }}</a></p>
            <p><b>Description: </b>{{ account.description }}</p>
            <p><b>Billable: </b>{{ account.billable }}</p>
            <p><b>Discretionary: </b>{{ account.discretionary }}</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <h2>Positions</h2>
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Security</th>
                            <th>Quantity</th>
                            <th>Cost Basis</th>
                            <th>View Position</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for position in positions %}
                        <tr>
                            <td><a href="{{ url_for('security.view_security', security_id=position.security_id) }}">{{ position.get_security_symbol() }}</a></td>
                            <td>{{ position.quantity }}</td>
                            <td>{{ position.cost_basis }}</td>
                            <td><a href="{{ url_for('transaction.view_position', position_id=position.id) }}">View Position</a></td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <h2>Transactions</h2>
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Date</th>
                            <th>Type</th>
                            <th>Security</th>
                            <th>Quantity</th>
                            <th>Share Price</th>
                            <th>Gross Amount</th>
                            <th>Description</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for transaction in transactions %}
                        <tr>
                            <td><a href="{{ url_for('transaction.view_transaction', transaction_id=transaction.id) }}">{{ transaction.date }}</a></td>
                            <td>{{ transaction.type }}</td>
                            <td><a href="{{ url_for('security.view_security', security_id=transaction.security_id) }}">{{ transaction.get_security_symbol() }}</a></td>
                            <td>{{ transaction.quantity }}</td>
                            <td>{{ transaction.share_price }}</td>
                            <td>{{ transaction.gross_amount }}</td>
                            <td>{{ transaction.description }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <h2>Account Snapshots</h2>
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Date</th>
                            <th>Name</th>
                            <th>Market Value</th>
                            <th>Quarter</th>
                            <th>Group</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for snapshot in snapshots %}
                        <tr>
                            <td>{{ snapshot.date }}</td>
                            <td><a href="{{ url_for('billing.view_account_snapshot', snapshot_id=snapshot.id) }}">{{ snapshot.name }}</a></td>
                            <td>{{ snapshot.market_value }}</td>
                            <td><a href="{{ url_for('billing.view_quarter', quarter_id=snapshot.quarter_id) }}">{{ snapshot.quarter_name }}</a></td>
                            <td><a href="{{ url_for('billing.view_group_snapshot', snapshot_id=snapshot.group_snapshot_id) }}">{{ snapshot.group_name }}</a></td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

app/account/templates/view_account_snapshot.html
{% extends "base.html" %}

{% block app_content %}
    <h1>Account Snapshot</h1>
    <div class="row">
        <div class="col-md-12">
            <div class="table-responsive">
                <table class="table">
                    <tr>
                        <td>Account Number</td>
                        <td><a href="{{ url_for('account.view_account', account_id=account.id) }}">{{ account.account_number }}</a></td>
                    </tr>
                    <tr>
                        <td>Account Description</td>
                        <td>{{ account.description }}</td>
                    </tr>
                    <tr>
                        <td>Client</td>
                        <td><a href="{{ url_for('client.view_client', client_id=account.client_id) }}">{{ account.get_client_name() }}</a></td>
                    </tr>
                    <tr>
                        <td>Group</td>
                        {% if snapshot.assigned_group() %}
                        <td><a href="{{ url_for('client.view_group', group_id=snapshot.group_id) }}">{{ snapshot.get_group_name() }}</a></td>
                        {% else %}
                        <td>Unassigned</td>
                        {% endif %}
                    </tr>
                    <tr>
                        <td>Market Value</td>
                        <td>{{ snapshot.market_value }}</td>
                    </tr>
                    <tr>
                        <td>Quarter</td>
                        <td><a href="{{ url_for('billing.view_quarter', quarter_id=snapshot.quarter_id) }}">{{ snapshot.get_quarter_name() }}</a></td>
                    </tr>
                    <tr>
                        <td>Date</td>
                        <td>{{ snapshot.date }}</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

app/account/templates/view_account_snapshots.html
{% extends "base.html" %}

{% block app_content %}
    <h1>Account Snapshots</h1>
    <div class="table-responsive">
        <table class="table">
            <thead>
                <tr>
                    <th>Account Number</th>
                    <th>Client</th>
                    <th>Group</th>
                    <th>Market Value</th>
                    <th>Quarter</th>
                    <th>Date (View Snapshot)</th>
                    <th>Delete Snapshot</th>
                </tr>
            </thead>
            <tbody>
            {% for snapshot in snapshots %}
                {% with account=snapshot.get_account() %}
                <tr>
                    <td><a href="{{ url_for('account.view_account', account_id=account.id) }}">{{ account.account_number }}</a></td>
                    <td><a href="{{ url_for('client.view_client', client_id=account.client_id) }}">{{ account.get_client_name() }}</a></td>
                    {% if snapshot.assigned_group() %}
                        <td><a href="{{ url_for('client.view_group', group_id=snapshot.group_id) }}">{{ snapshot.get_group_name() }}</a></td>
                    {% else %}
                        <td>Unassigned</td>
                    {% endif %}
                    <td>{{ snapshot.market_value }}</td>
                    <td><a href="{{ url_for('billing.view_quarter', quarter_id=snapshot.quarter_id) }}">{{ snapshot.get_quarter_name() }}</a></td>
                    <td><a href="{{ url_for('account.view_account_snapshot', snapshot_id=snapshot.id) }}">{{ snapshot.date }}</a></td>
                    <td><a href="{{ url_for('account.delete_account_snapshot', snapshot_id=snapshot.id) }}" class="btn btn-danger" role="button">Delete</a></td>
                </tr>
                {% endwith %}
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

app/account/templates/view_accounts.html
{% extends "base.html" %}

{% block app_content %}
    <h1>Accounts</h1>
    <div class="table-responsive">
        <table class="table">
            <thead>
                <tr>
                    <th>Custodian</th>
                    <th>Account Number</th>
                    <th>Description</th>
                    <th>Client</th>
                    <th>Group</th>
                    <th>Billable</th>
                    <th>Discretionary</th>
                    <th>Delete Account</th>
                </tr>
            </thead>
            <tbody>
            {% for account in accounts %}
                <tr>
                    <td><a href="{{ url_for('account.view_custodian', custodian_id=account.custodian_id) }}">{{ account.get_custodian_name() }}</a></td>
                    <td><a href="{{ url_for('account.view_account', account_id=account.id) }}">{{ account.account_number }}</a></td>
                    <td>{{ account.description }}</td>
                    <td><a href="{{ url_for('client.view_client', client_id=account.client_id) }}">{{ account.get_client_name() }}</a></td>
                    <td><a href="{{ url_for('client.view_group', group_id=account.group_id) }}">{{ account.get_group_name() }}</a></td>
                    <td>{{ account.billable }}</td>
                    <td>{{ account.discretionary }}</td>
                    <td><a href="{{ url_for('account.delete_account', account_id=account.id) }}" class="btn btn-danger" role="button">Delete</a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

app/account/templates/view_custodian.html
{% extends "base.html" %}

{% block app_content %}
    <h1>Custodian Dashboard</h1>
    <div class="row">
        <div class="col-md-4">
            <h3>{{ custodian.name }}</h3>
            <p><b>Description: </b>{{ custodian.description }}</p>
        </div>
    </div>
    <div class="table-responsive">
        <table class="table">
            <thead>
                <tr>
                    <th>Client Name</th>
                    <th>Account Number</th>
                    <th>Description</th>
                </tr>
            </thead>
            <tbody>
            {% for account in accounts %}
                <tr>
                    <td><a href="{{ url_for('client.view_client', client_id=account.client_id) }}">{{ account.get_client_name() }}</a></td>
                    <td><a href="{{ url_for('account.view_account', account_id=account.id) }}">{{ account.account_number }}</a></td>
                    <td>{{ account.description }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

app/account/templates/view_custodians.html
{% extends "base.html" %}

{% block app_content %}
    <h1>Custodians</h1>
    <div class="table-responsive">
        <table class="table">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Description</th>
                </tr>
            </thead>
            <tbody>
            {% for custodian in custodians %}
                <tr>
                    <td><a href="{{ url_for('account.view_custodian', custodian_id=custodian.id) }}">{{ custodian.name }}</a></td>
                    <td>{{ custodian.description }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}