app/transaction/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileRequired, FileAllowed
from wtforms import (StringField, PasswordField, BooleanField, SubmitField, SelectField, RadioField,
                     DateField, SelectMultipleField, widgets, FloatField)
from wtforms.validators import InputRequired, ValidationError, Email, EqualTo
from app.models import User, Security


class TransactionForm(FlaskForm):
    date = DateField('Date')
    type = SelectField('Type')
    security = SelectField('Security')
    quantity = FloatField('Quantity', validators=[InputRequired()])
    share_price = FloatField('Share Price', validators=[InputRequired()])
    gross_amount = FloatField('Gross Amount', validators=[InputRequired()])
    description = StringField('Description')
    submit = SubmitField('Save')


class UploadFileForm(FlaskForm):
    upload_file = FileField('File', validators=[FileRequired(), FileAllowed(['csv'], '.csv only')])
    submit = SubmitField('Upload')


class ExportToFileForm(FlaskForm):
    filename = StringField('Filename', validators=[InputRequired()])
    submit = SubmitField('Export')

app/transaction/__init__.py
from flask import Blueprint

bp = Blueprint('transaction', __name__, template_folder='templates')

from app.transaction import routes

app/transaction/routes.py
from flask import render_template, flash, redirect, url_for
from flask_login import login_required
from app import db
from app.models import (Account, Security, Position, Transaction)
from app.transaction.forms import (TransactionForm, UploadFileForm, ExportToFileForm)
from app.transaction import bp
from app.route_helpers import (get_security_choices,
                               process_transaction_csv_file)
from datetime import date
import os
from werkzeug.utils import secure_filename


@bp.route('/view_positions')
@login_required
def view_positions():
    positions = Position.query.all()
    return render_template('view_positions.html', title='Positions', positions=positions)


@bp.route('/view_position/<position_id>')
@login_required
def view_position(position_id):
    position = Position.query.get(int(position_id))
    transactions = position.transactions
    return render_template('view_position.html', title='Position', position=position, transactions=transactions)


@bp.route('/view_transactions')
@login_required
def view_transactions():
    transactions = Transaction.query.all()
    return render_template('view_transactions.html', title='Transactions', transactions=transactions)


@bp.route('/view_transaction/<transaction_id>')
@login_required
def view_transaction(transaction_id):
    transaction = Transaction.query.get(int(transaction_id))
    return render_template('view_transaction.html', title='Transaction', transaction=transaction)


@bp.route('/add_transaction/<account_id>', methods=['GET', 'POST'])
@login_required
def add_transaction(account_id):
    account = Account.query.get(int(account_id))
    form = TransactionForm()
    form.security.choices = get_security_choices()
    type_choices = [('BUY', 'Buy'), ('SELL', 'Sell')]
    form.type.choices = type_choices
    if form.validate_on_submit():
        security = Security.query.get(int(form.security.data))
        position = Position.query.filter_by(account_id=account.id, security_id=security.id).first()
        if position is None:
            position = Position(quantity=0, cost_basis=0, account_id=account.id, security_id=security.id)
            db.session.add(position)
            db.session.commit()
        transaction = Transaction(date=form.date.data, type=form.type.data, quantity=form.quantity.data,
                                  share_price=form.share_price.data, gross_amount=form.gross_amount.data,
                                  description=form.description.data, account_id=account.id, security_id=security.id,
                                  position_id=position.id)
        position.add_transaction(transaction_type=transaction.type, quantity=transaction.quantity,
                                 gross_amount=transaction.gross_amount)
        db.session.add(transaction)
        db.session.add(position)
        db.session.commit()
        return redirect(url_for('account.view_account', account_id=account_id))
    return render_template('add_transaction.html', title='Add Transaction', form=form, account=account)


@bp.route('/add_transaction_redirect')
@login_required
def add_transaction_redirect():
    flash('Choose an account')
    return redirect(url_for('account.view_accounts'))


@bp.route('/edit_transaction/<transaction_id>', methods=['GET', 'POST'])
@login_required
def edit_transaction(transaction_id):
    transaction = Transaction.query.get(int(transaction_id))
    form = TransactionForm()
    if form.validate_on_submit():
        transaction.date = form.date.data
        transaction.type = form.type.data
        transaction.quantity = form.quantity.data
        transaction.share_price = form.share_price.data
        transaction.gross_amount = form.gross_amount.data
        transaction.description = form.description.data
        position = Position.query.get(transaction.position_id)
        position.recreate_position()
        db.session.add(transaction)
        db.session.add(position)
        db.session.commit()
        return redirect(url_for('transaction.view_transaction', transaction_id=transaction.id))
    form.date.data = transaction.date
    form.type.data = transaction.type
    form.quantity.data = transaction.quantity
    form.share_price.data = transaction.share_price
    form.gross_amount.data = transaction.gross_amount
    form.description.data = transaction.description
    return render_template('edit_transaction.html', title='Edit Transaction', form=form)


@bp.route('/upload_transactions', methods=['GET', 'POST'])
@login_required
def upload_transactions():
    form = UploadFileForm()
    if form.validate_on_submit():
        process_transaction_csv_file(file_object=form.upload_file.data)
        return redirect(url_for('transaction.view_transactions'))
    return render_template('upload_transaction_file.html', title='Upload Transaction File', form=form)


@bp.route('/export_transactions', methods=['GET', 'POST'])
@login_required
def export_transactions():
    form = ExportToFileForm()
    if form.validate_on_submit():
        filename = os.path.join('exports/' + secure_filename(form.filename.data))
        with open(filename, 'w') as export_file:
            header = ('Date,Account Number,Type,Symbol,Name,Quantity,' +
                      'Share Price,Gross Amount,Description\n')
            export_file.write(header)
            transactions = Transaction.query.all()
            for transaction in transactions:
                export_file.write(transaction.export_transactions_csv() + '\n')
        return redirect(url_for('main.index'))
    return render_template('export_transactions.html', title='Export Transactions', form=form)


@bp.route('/delete_transaction/<transaction_id>')
@login_required
def delete_transaction(transaction_id):
    transaction = Transaction.query.get(int(transaction_id))
    position = Position.query.get(int(transaction.position_id))
    position.remove_transaction(transaction_id=transaction.id)
    db.session.delete(transaction)
    db.session.add(position)
    db.session.commit()
    return redirect(url_for('transaction.view_transactions'))

app/transaction/templates/add_transaction.html
{% extends "base.html" %}
{% from 'bootstrap/form.html' import render_form %}

{% block app_content %}
    <h1>Add Transaction</h1>
    <p><b>Instructions: </b>Use the form below to add a new transaction</p>
    <div class="row">
        <div class="col-md-4">
            {{ render_form(form) }}
        </div>
    </div>
{% endblock %}

app/transaction/templates/edit_transaction.html
{% extends "base.html" %}
{% from 'bootstrap/form.html' import render_form %}

{% block app_content %}
    <h1>Edit Transaction</h1>
    <p><b>Instructions: </b>Use the form below to edit the transaction.</p>
    <div class="row">
        <div class="col-md-4">
            {{ render_form(form) }}
        </div>
    </div>
{% endblock %}

app/transaction/templates/export_transactions.html
{% extends "base.html" %}
{% from 'bootstrap/form.html' import render_form %}

{% block app_content %}
    <h1>Export Transactions to CSV</h1>
    <div class="row">
        <div class="col-md-4">
            {{ render_form(form) }}
        </div>
    </div>
{% endblock %}

app/transaction/templates/upload_transaction_file.html
{% extends "base.html" %}
{% from 'bootstrap/form.html' import render_form %}

{% block app_content %}
    <h1>Upload Transaction File</h1>
    <p><b>Instructions: </b>Use the form to upload a .csv file.</p>
    <p>Date | Account Number | Type | Symbol | Name | Quantity | Share Price | Gross Amount | Description</p>
    <div class="row">
        <div class="col-md-4">
            {{ render_form(form) }}
        </div>
    </div>
{% endblock %}

app/transaction/templates/view_position.html
{% extends "base.html" %}

{% block app_content %}
    <h1>Position Dashboard</h1>
    <div class="row">
        <div class="col-md-12">
            <h2>Position Details</h2>
            <div class="table-responsive">
                <table class="table">
                    <tr>
                        <td>Account Number</td>
                        <td><a href="{{ url_for('account.view_account', account_id=position.account_id) }}">{{ position.get_account_number() }}</a></td>
                    </tr>
                    <tr>
                        <td>Symbol</td>
                        <td><a href="{{ url_for('security.view_security', security_id=position.security_id) }}">{{ position.get_security_symbol() }}</a></td>
                    </tr>
                    <tr>
                        <td>Quantity</td>
                        <td>{{ position.quantity }}</td>
                    </tr>
                    <tr>
                        <td>Cost Basis</td>
                        <td>{{ position.cost_basis }}</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <h2>Transactions</h2>
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Date</th>
                            <th>Account Number</th>
                            <th>Type</th>
                            <th>Quantity</th>
                            <th>Share Price</th>
                            <th>Gross Amount</th>
                            <th>Description</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for transaction in transactions %}
                        <tr>
                            <td><a href="{{ url_for('transaction.view_transaction', transaction_id=transaction.id) }}">{{ transaction.date }}</a></td>
                            <td><a href="{{ url_for('account.view_account', account_id=transaction.account_id) }}">{{ transaction.get_account_number() }}</a></td>
                            <td>{{ transaction.type }}</td>
                            <td>{{ transaction.quantity }}</td>
                            <td>{{ transaction.share_price }}</td>
                            <td>{{ transaction.gross_amount }}</td>
                            <td>{{ transaction.description }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

app/transaction/templates/view_positions.html
{% extends "base.html" %}

{% block app_content %}
    <h1>Positions</h1>
    <div class="table-responsive">
        <table class="table">
            <thead>
                <tr>
                    <th>Account Number</th>
                    <th>Security</th>
                    <th>Quantity</th>
                    <th>Cost Basis</th>
                    <th>View Position</th>
                </tr>
            </thead>
            <tbody>
            {% for position in positions %}
                <tr>
                    <td><a href="{{ url_for('account.view_account', account_id=position.account_id) }}">{{ position.get_account_number() }}</a></td>
                    <td><a href="{{ url_for('security.view_security', security_id=position.security_id) }}">{{ position.get_security_symbol() }}</a></td>
                    <td>{{ position.quantity }}</td>
                    <td>{{ position.cost_basis }}</td>
                    <td><a href="{{ url_for('transaction.view_position', position_id=position.id) }}">View Position</a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

app/transaction/templates/view_securities.html
{% extends "base.html" %}

{% block app_content %}
    <h1>Securities</h1>
    <div class="table-responsive">
        <table class="table">
            <thead>
                <tr>
                    <th>Symbol</th>
                    <th>Name</th>
                    <th>Description</th>
                </tr>
            </thead>
            <tbody>
            {% for security in securities %}
                <tr>
                    <td><a href="{{ url_for('transaction.view_security', security_id=security.id) }}">{{ security.symbol }}</a></td>
                    <td>{{ security.name }}</td>
                    <td>{{ security.description }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

app/transaction/templates/view_security.html
{% extends "base.html" %}

{% block app_content %}
    <h1>Security Dashboard</h1>
    <div class="row">
        <div class="col-md-4">
            <a href="{{ url_for('transaction.edit_security', security_id=security.id) }}" class="btn btn-primary" role="button">Edit Security</a>
            <a href="{{ url_for('transaction.update_security_data', security_id=security.id) }}" class="btn btn-primary" role="button">Update Security Data</a>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <h2>Security Information</h2>
            <div class="table-responsive">
                <table class="table">
                    <tbody>
                        <tr>
                            <td>Symbol</td>
                            <td>{{ security.symbol }}</td>
                        </tr>
                        <tr>
                            <td>Name</td>
                            <td>{{ security.name }}</td>
                        </tr>
                        <tr>
                            <td>Description</td>
                            <td>{{ security.description }}</td>
                        </tr>
                        <tr>
                            <td>Last Updated</td>
                            <td>{{ security.last_snapshot }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <h2>Positions</h2>
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Account</th>
                            <th>Quantity</th>
                            <th>Cost Basis</th>
                            <th>View Position</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for position in positions %}
                        <tr>
                            <td><a href="{{ url_for('account.view_account', account_id=position.account_id) }}">{{ position.get_account_number() }}</a></td>
                            <td>{{ position.quantity }}</td>
                            <td>{{ position.cost_basis }}</td>
                            <td><a href="{{ url_for('transaction.view_position', position_id=position.id) }}">View Position</a></td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <h2>Transactions</h2>
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Date</th>
                            <th>Account Number</th>
                            <th>Type</th>
                            <th>Quantity</th>
                            <th>Share Price</th>
                            <th>Gross Amount</th>
                            <th>Description</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for transaction in transactions %}
                        <tr>
                            <td><a href="{{ url_for('transaction.view_transaction', transaction_id=transaction.id) }}">{{ transaction.date }}</a></td>
                            <td><a href="{{ url_for('account.view_account', account_id=transaction.account_id) }}">{{ transaction.get_account_number() }}</a></td>
                            <td>{{ transaction.type }}</td>
                            <td>{{ transaction.quantity }}</td>
                            <td>{{ transaction.share_price }}</td>
                            <td>{{ transaction.gross_amount }}</td>
                            <td>{{ transaction.description }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <h2>Security Snapshots</h2>
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Date</th>
                            <th>Open</th>
                            <th>Close</th>
                            <th>Low</th>
                            <th>High</th>
                            <th>Volume</th>
                            <th>Delete Snapshot</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for snapshot in security.snapshots %}
                        <tr>
                            <td><a href="{{ url_for('transaction.view_security_snapshot', snapshot_id=snapshot.id) }}">{{ snapshot.data_date }}</a></td>
                            <td>{{ snapshot.open_value }}</td>
                            <td>{{ snapshot.close_value }}</td>
                            <td>{{ snapshot.low_value }}</td>
                            <td>{{ snapshot.high_value }}</td>
                            <td>{{ snapshot.volume }}</td>
                            <td><a href="{{ url_for('transaction.delete_security_snapshot', snapshot_id=snapshot.id) }}" class="btn btn-primary" role="button">Delete</a></td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

app/transaction/templates/view_security_snapshot.html
{% extends "base.html" %}

{% block app_content %}
    <h1>Security Snapshot</h1>
    <h2><a href="{{ url_for('transaction.view_security', security_id=snapshot.security_id) }}">{{ snapshot.symbol }}</a> - {{ snapshot.data_date }}</h2>
    <div class="row">
        <div class="col-md-12">
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th></th>
                            <th>Value</th>
                            <th>Hundred Day Average</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>Open</td>
                            <td>{{ snapshot.open_value }}</td>
                            <td>{{ snapshot.hundred_day_average_open }}</td>
                        </tr>
                        <tr>
                            <td>Close</td>
                            <td>{{ snapshot.close_value }}</td>
                            <td>{{ snapshot.hundred_day_average_close }}</td>
                        </tr>
                        <tr>
                            <td>High</td>
                            <td>{{ snapshot.high_value }}</td>
                            <td>{{ snapshot.hundred_day_average_high }}</td>
                        </tr>
                        <tr>
                            <td>Low</td>
                            <td>{{ snapshot.low_value }}</td>
                            <td>{{ snapshot.hundred_day_average_low }}</td>
                        </tr>
                        <tr>
                            <td>Volume</td>
                            <td>{{ snapshot.volume }}</td>
                            <td>{{ snapshot.hundred_day_average_volume }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

app/transaction/templates/view_transaction.html
{% extends "base.html" %}

{% block app_content %}
    <h1>Transaction Dashboard</h1>
    <div class="row">
        <div class="col-md-4">
            <a href="{{ url_for('transaction.view_position', position_id=transaction.position_id) }}" class="btn btn-primary" role="button">View Position</a>
            <a href="{{ url_for('transaction.edit_transaction', transaction_id=transaction.id) }}" class="btn btn-primary" role="button">Edit Transaction</a>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <h2>Transaction Details</h2>
            <p><b>Date: </b>{{ transaction.date }}</p>
            <p><b>Account: </b><a href="{{ url_for('account.view_account', account_id=transaction.account_id) }}">{{ transaction.get_account_number() }}</a></p>
            <p><b>Type: </b>{{ transaction.type }}</p>
            <p><b>Security: </b><a href="{{ url_for('security.view_security', security_id=transaction.security_id) }}">{{ transaction.get_security_symbol() }}</a></p>
            <p><b>Quantity: </b>{{ transaction.quantity }}</p>
            <p><b>Share Price: </b>{{ transaction.share_price }}</p>
            <p><b>Gross Amount: </b>{{ transaction.gross_amount }}</p>
            <p><b>Description: </b>{{ transaction.description }}</p>
        </div>
    </div>
{% endblock %}

app/transaction/templates/view_transactions.html
{% extends "base.html" %}

{% block app_content %}
    <h1>Transactions</h1>
    <div class="table-responsive">
        <table class="table">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Account Number</th>
                    <th>Type</th>
                    <th>Security</th>
                    <th>Quantity</th>
                    <th>Share Price</th>
                    <th>Gross Amount</th>
                    <th>Description</th>
                    <th>Delete Transaction</th>
                </tr>
            </thead>
            <tbody>
            {% for transaction in transactions %}
                <tr>
                    <td><a href="{{ url_for('transaction.view_transaction', transaction_id=transaction.id) }}">{{ transaction.date }}</a></td>
                    <td><a href="{{ url_for('account.view_account', account_id=transaction.account_id) }}">{{ transaction.get_account_number() }}</a></td>
                    <td>{{ transaction.type }}</td>
                    <td><a href="{{ url_for('transaction.view_security', security_id=transaction.security_id) }}">{{ transaction.get_security_symbol() }}</a></td>
                    <td>{{ transaction.quantity }}</td>
                    <td>{{ transaction.share_price }}</td>
                    <td>{{ transaction.gross_amount }}</td>
                    <td>{{ transaction.description }}</td>
                    <td><a href="{{ url_for('transaction.delete_transaction', transaction_id=transaction.id) }}" class="btn btn-danger" role="button">Delete</a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}